### ISSUE TITLE
All boost libraries containing cpp files appear to missing srcs diective in their BUILD files

### ISSUE THREAD

**Issue by elitegregsp** [bazelboost/registry#169]
Looking at a number of the bazelboost boost modules that contain cpp files (e.g. regex and system for instance), the BUILD scripts cc_library call is missing the srcs parameter so the library .a/.so files aren't created.

**Comment by zaucy** [comment]
Thanks for trying out bazelboost!

Yes that's right. A lot of the bazel boost modules were automatically generated and some files were missed.

Most bazel boost modules that have sources require a bit of care to support the various platforms/configurations available. 

I'd suggest making an issue on each individual repository as you run into them. I've been updating each repository as I (or someone else) requires them and runs into issues. Contributions are welcome!
